Retry changes

diff --git a/tooling/bundler/src/bundle/macos/templates/dmg/bundle_dmg b/tooling/bundler/src/bundle/macos/templates/dmg/bundle_dmg
--- a/tooling/bundler/src/bundle/macos/templates/dmg/bundle_dmg
+++ b/tooling/bundler/src/bundle/macos/templates/dmg/bundle_dmg
@@ -248,12 +248,40 @@ if [[ -n "$DISK_IMAGE_SIZE" ]]; then
 	CUSTOM_SIZE="-size ${DISK_IMAGE_SIZE}m"
 fi
 
-if [ $SANDBOX_SAFE -eq 0 ]; then
-	hdiutil create ${HDIUTIL_VERBOSITY} -srcfolder "$SRC_FOLDER" -volname "${VOLUME_NAME}" -fs HFS+ -fsargs "-c c=64,a=16,e=16" -format UDRW ${CUSTOM_SIZE} "${DMG_TEMP_NAME}"
-else
-	hdiutil makehybrid ${HDIUTIL_VERBOSITY} -default-volume-name "${VOLUME_NAME}" -hfs -o "${DMG_TEMP_NAME}" "$SRC_FOLDER"
-	hdiutil convert -format UDRW -ov -o "${DMG_TEMP_NAME}" "${DMG_TEMP_NAME}"
-	DISK_IMAGE_SIZE_CUSTOM=$DISK_IMAGE_SIZE
+MAX_RETRIES=3 
+
+RETRY_DELAY=5 
+
+for ((i=0; i<$MAX_RETRIES; i++)); do
+	echo "Attempt $((i+1)) if $MAX_RETRIES to create the disk image..."
+
+	if [ $SANDBOX_SAFE -eq 0 ]; then
+		hdiutil create ${HDIUTIL_VERBOSITY} -srcfolder "$SRC_FOLDER" -volname "${VOLUME_NAME}" -fs HFS+ -fsargs "-c c=64,a=16,e=16" -format UDRW ${CUSTOM_SIZE} "${DMG_TEMP_NAME}"
+	else
+		hdiutil makehybrid ${HDIUTIL_VERBOSITY} -default-volume-name "${VOLUME_NAME}" -hfs -o "${DMG_TEMP_NAME}" "$SRC_FOLDER"
+		hdiutil convert -format UDRW -ov -o "${DMG_TEMP_NAME}" "${DMG_TEMP_NAME}"
+		DISK_IMAGE_SIZE_CUSTOM=$DISK_IMAGE_SIZE
+	fi
+	HDIUTIL_SUCCESS=$?
+	echo "$HDIUTIL_OUTPUT"
+
+	# Check for success or specific error
+
+	if [[ $HDIUTIL_SUCCESS -eq 0 ]]; then
+		echo "Disk image created successfully" 
+		break
+	elif [[ $HDIUTIL_SUCCESS -eq 16 ]]; then
+		echo "Disk image creation failed with error code 16 (EBUSY). Retrying in $RETRY_DELAY seconds..."
+		sleep $RETRY_DELAY
+	else
+		echo "Disk image creation failed with error code $HDIUTIL_SUCCESS. Exiting..."
+		exit 1
+	fi
+done
+
+if [[ $HDIUTIL_SUCCESS -ne 0 ]]; then
+	echo "Disk image creation failed after $MAX_RETRIES attempts. Exiting..."
+	exit 1
 fi
 
 # Get the created DMG actual size
